import os

import quantumsim.qasm as qasm

qubit_test_pars = {
    'T1': 30000,
    'T2': 30000,
    'frac1_0': 0.01,
    'frac1_1': 0.99}

deutsch_josza_test_qasm = """
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 7

.DJ1
   prepz q0
   prepz q2
   ry90 q0
   rym90 q2
   ry90 q0
   ry90 q2
   measure q0
   measure q2

.DJ2
   prepz q0
   prepz q2
   ry90 q0
   rym90 q2
   rx180 q2
   ry90 q0
   ry90 q2
   measure q0
   measure q2

.DJ3
   prepz q0
   prepz q2
   ry90 q0
   rym90 q2
   ry90 q2
   rx180 q0
   rx180 q2
   qwait 5
   fl_cw_01 q2,q0
   qwait 10
   rx180 q0
   ry90 q2
   ry90 q0
   ry90 q2
   measure q0
   measure q2

.DJ4
   prepz q0
   prepz q2
   ry90 q0
   rym90 q2
   rym90 q2
   qwait 5
   fl_cw_01 q2,q0
   qwait 10
   rx180 q2
   rym90 q2
   ry90 q0
   ry90 q2
   measure q0
   measure q2
        """

allxy1_qasm = """
qubits 2

.allXY0
   prepz q0
   measure q0

.allXY1
   prepz q0
   rx180 q0
   rx180 q0
   measure q0

.allXY2
   prepz q0
   ry180 q0
   ry180 q0
   measure q0

.allXY3
   prepz q0
   rx180 q0
   ry180 q0
   measure q0

.allXY4
   prepz q0
   ry180 q0
   rx180 q0
   measure q0

.allXY5
   prepz q0
   rx90 q0
   measure q0

.allXY6
   prepz q0
   ry90 q0
   measure q0

.allXY7
   prepz q0
   rx90 q0
   ry90 q0
   measure q0

.allXY8
   prepz q0
   ry90 q0
   rx90 q0
   measure q0

.allXY9
   prepz q0
   rx90 q0
   ry180 q0
   measure q0

.allXY10
   prepz q0
   ry90 q0
   rx180 q0
   measure q0

.allXY11
   prepz q0
   rx180 q0
   ry90 q0
   measure q0

.allXY12
   prepz q0
   ry180 q0
   rx90 q0
   measure q0

.allXY13
   prepz q0
   rx90 q0
   rx180 q0
   measure q0

.allXY14
   prepz q0
   rx180 q0
   rx90 q0
   measure q0

.allXY15
   prepz q0
   ry90 q0
   ry180 q0
   measure q0

.allXY16
   prepz q0
   ry180 q0
   ry90 q0
   measure q0

.allXY17
   prepz q0
   rx180 q0
   measure q0

.allXY18
   prepz q0
   ry180 q0
   measure q0

.allXY19
   prepz q0
   rx90 q0
   rx90 q0
   measure q0

.allXY20
   prepz q0
   ry90 q0
   ry90 q0
   measure q0
"""


test_allxy_fused_qasm = """
qubits 7

.fused_kernels
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q0 | i q2 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q0 | i q2 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q2 | rx180 q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q2 | rx180 q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q2 | ry180 q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q2 | ry180 q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q2 | ry180 q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q2 | ry180 q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q2 | rx180 q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q2 | rx180 q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q2 | ry90 q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q2 | ry90 q0 }
    qwait 1
    { i q0 | ry90 q2 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { i q2 | rx90 q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { i q2 | rx90 q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q2 | prepz q0 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q2 | ry180 q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { rx90 q0 | i q2 }
    qwait 1
    { i q2 | ry180 q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { i q2 | rx180 q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { i q2 | rx180 q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q2 | ry90 q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q2 | ry90 q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q2 | rx90 q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q2 | rx90 q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q2 | rx180 q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q2 | rx180 q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q2 | rx90 q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q2 | rx90 q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { i q2 | ry180 q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { ry180 q0 | i q2 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q2 | ry90 q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q2 | ry90 q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx180 q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { i q0 | ry90 q2 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry180 q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q2 | rx90 q0 }
    qwait 1
    { rx180 q2 | i q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q2 | prepz q0 }
    qwait 9999
    { i q2 | rx90 q0 }
    qwait 1
    { i q2 | rx90 q0 }
    qwait 1
    { ry180 q2 | i q0 }
    qwait 1
    { i q0 | i q2 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { ry90 q0 | i q2 }
    qwait 1
    { i q2 | ry90 q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { rx90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
    { prepz q0 | prepz q2 }
    qwait 9999
    { i q2 | ry90 q0 }
    qwait 1
    { i q2 | ry90 q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { ry90 q2 | i q0 }
    qwait 1
    { measure q0 | measure q2 }
    qwait 249
"""


class TestQASMParser:
    def test_dj_qasm(self):

        parser = qasm.QASMParser(
            qubit_parameters={
                'q0': qubit_test_pars,
                'q2': qubit_test_pars,
                'default': qubit_test_pars})

        parser.parse(deutsch_josza_test_qasm)

        print([c.title for c in parser.circuits])

        assert len(parser.circuits) == 4

        for c in parser.circuits:
            assert len(c.qubits) == 2

    def test_allxy1_qasm(self):
        parser = qasm.QASMParser(
            qubit_parameters={
                'default': qubit_test_pars})

        parser.parse(allxy1_qasm)

        for c in parser.circuits:
            assert len(c.qubits) == 1

        print([c.title for c in parser.circuits])
        assert len(parser.circuits) == 21

    def test_fused_kernel(self):
        parser = qasm.QASMParser(
            qubit_parameters={
                'default': qubit_test_pars})

        parser.parse(test_allxy_fused_qasm)

        for c in parser.circuits:
            assert len(c.qubits) == 2

        assert len(parser.circuits) == 42


class TestConfigurableParser:

    def test_config_merging(self):
        config = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                              'config_qasm_5q.json')
        config_override = {
            'instructions': {
                'i q0': {
                    'duration': 200,
                }
            },
            'gate_decompositions': {}
        }

        parser1 = qasm.ConfigurableParser(config)
        parser2 = qasm.ConfigurableParser(config, config_override)

        assert len(parser1._instructions) == len(parser2._instructions)
        unchanged = parser1._instructions.pop('i q0')
        changed = parser2._instructions.pop('i q0')
        assert unchanged['duration'] == 100
        assert changed['duration'] == 200
        assert unchanged['kraus_repr'] == changed['kraus_repr']
        assert unchanged['qubits'] == changed['qubits']
        assert len(parser1._decomposers) == len(parser2._decomposers)
